### ISSUE TITLE
UserResolver.AnonymousBucket is not automatically created

### ISSUE THREAD

**Issue by bencameron** [Developer-Autodesk/forge-configurator-inventor#268]
When running the application locally, an exception is thrown due to a bucket not existing in OSS. After attaching the debugger, I was able to see that it is when trying to access the AnonymousBucket.  The UserResolver.GetBucketAsync() has an argument for whether or not to try to create the requested bucket, but this logic is not used in the case of the AnonymousBucket.  After creating this bucket manually, the exception is no longer thrown.

**Comment by hradilm** [comment]
Hello.

AnonymousBucket is created and populated by default projects during application initialization. This process needs to be invoked using command line arguments "clear=true" "initialize=true" when running the "dotnet run". We have it mentioned in the readme, but it is not obvious when you read the readme sequentialy from the top to bottom, so we will fix that.

For your case I would just build the solution and run from command line:
`cd WebApplication`
`dotnet run clear=true initialize=true`
This process clears the old data, creates and uploads FDA AppBudles and Activities and populates the OSS bucket with the initial projects. It takes about 2 minutes to complete, so be patient please. Once it is done it starts the Web server and waits for the client connection (from browser). At this point you can checkout the application by visiting https://localhost:5001 or just stop it and start the debugging session. You do not need to perform the initialization again.

Michal

**Comment by bencameron** [comment]
Thanks, that makes sense.  I was running with the debugger from Visual Studio, so I didn't follow the instructions under "Run The Web Application Without Debugging".  I see now that those were intended to be a sequential set of steps to follow rather than different options for how to run it.
